### ISSUE TITLE
Use entity attribute

### ISSUE THREAD

**Issue by disforw** [basschipper/homeassistant-generic-hygrostat#25]
Is it possible to use an entities humidity attribute to create a generic hydrostat?
For example I have a thermostat (climate entity), that includes a humidity attribute.

**Comment by basschipper** [comment]
Yes, but not directly. You should create a separate entity from that attr first.

Something like:
```yaml
template:
  - sensor:
      - name: "Bathroom humidity"
        unit_of_measurement: "%"
        state: "{{ state_attr('sensor.bathroom_all_in_one', 'humidity') }}"
```
