### ISSUE TITLE
Stopped working abruptly, v0.5.0

### ISSUE THREAD

**Issue by derekcentrico** [basschipper/homeassistant-generic-hygrostat#28]
Good morning.  At some point yesterday, the below warning started popping up.  The sensor in question is still attached and injecting data into HA.  It's a Aqara sensor through deCONZ should that be relevant.  I updated HA Core which rebooted Core, that's all I can think of.  

core-2021.8.7
supervisor-2021.06.8
Home Assistant OS 6.2

log:

> Logger: custom_components.generic_hygrostat.binary_sensor
> Source: custom_components/generic_hygrostat/binary_sensor.py:120
> Integration: generic_hygrostat (documentation)
> First occurred: 6:57:41 AM (1 occurrences)
> Last logged: 6:57:41 AM
> 
> Unknown humidity sensor 'sensor.master_bathroom_2'

configuration yaml:

```
binary_sensor:
- platform: generic_hygrostat
  name: Bathroom Hygrostat
  sensor: sensor.master_bathroom_2 # Source humidity sensor
  delta_trigger: 4 # Optional humidity swing to detect. Default = 3
  target_offset: 0 # Optional dehumidification target offset. Default = 3
  min_on_time: 300 # Optional min on time in seconds. Default = 0 seconds
  max_on_time: 5400 # Optional safety max on time in seconds. Default = 7200 seconds
  sample_interval: 300 # Optional time between taking humidity samples in seconds, default 300 seconds
  min_humidity: 54 # Optional minimum humidity to enable dehumidification. Default = 0
```

automation yaml:

```
- id: '1692801842292'
  alias: Master Bath Hygrostat On
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_hygrostat
    to: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.mast_bath_dehumidifier
- id: '1692801842293'
  alias: Master Bath Hygrostat Off
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_hygrostat
    to: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.mast_bath_dehumidifier
```
