### ISSUE TITLE
Not working and getting an error

### ISSUE THREAD

**Issue by dcf1999** [basschipper/homeassistant-generic-hygrostat#29]
So I'm getting this error in the log:

```
This error originated from a custom integration.

Logger: custom_components.generic_hygrostat.binary_sensor
Source: custom_components/generic_hygrostat/binary_sensor.py:120
Integration: generic_hygrostat (documentation)
First occurred: 11:26:22 AM (1 occurrences)
Last logged: 11:26:22 AM

Unknown humidity sensor 'sensor.bathroom_climate_humidity'
```

I installed via HACS and put the follwing in my config.yaml

```
binary_sensor:
- platform: generic_hygrostat
  name: Bathroom Hygrostat
  sensor: sensor.bathroom_climate_humidity # Source humidity sensor
  delta_trigger: 3 # Optional humidity swing to detect. Default = 3
  target_offset: 3 # Optional dehumidification target offset. Default = 3
  min_on_time: 300 # Optional min on time in seconds. Default = 0 seconds
  max_on_time: 2700 # Optional safety max on time in seconds. Default = 7200 seconds
  sample_interval: 300 # Optional time between taking humidity samples in seconds, default 300 seconds
  min_humidity: 30 # Optional minimum humidity to enable dehumidification. Default = 0
```

We ran the shower today and humidity went way up and it never triggered. On my UI I have the "bathroom hygrostat" on a card and it stayed off the whole time. even when the humidity spiked from 50 (standard) to 80 (during shower)

Any ideas?

**Comment by dcf1999** [comment]
this is my automation code:

```
alias: Bathroom Fan
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_hygrostat
    to: 'on'
    id: 'on'
  - platform: state
    entity_id: binary_sensor.bathroom_hygrostat
    to: 'off'
    id: 'off'
condition: []
action:
  - service: switch.turn_{{ trigger.id }}
    target:
      entity_id: switch.master_bathroom_fan
  - service: notify.notify
    data:
      title: Bathroom fan is {{ trigger.id }}
mode: single
```
