### ISSUE TITLE
2 fan and 2 bathrooms

### ISSUE THREAD

**Issue by offsaid** [basschipper/homeassistant-generic-hygrostat#31]
Hi! how to configure independently for two fans and two bathrooms?

**Comment by basschipper** [comment]
Just configure it twice:
```
binary_sensor:
- platform: generic_hygrostat
  name: Bathroom Hygrostat 1
  sensor: sensor.bathroom_climate_humidity_1
- platform: generic_hygrostat
  name: Bathroom Hygrostat 2
  sensor: sensor.bathroom_climate_humidity_2
```
