### ISSUE TITLE
My humidistat does not activate

### ISSUE THREAD

**Issue by pika28** [basschipper/homeassistant-generic-hygrostat#40]
Goodnight all,

First of all, thank you for this work. I installed the package from HACS. I added the following code but it doesn't work. My source is the Netatmo add-on sensor which updates data every 5-6 min on HAOS.

```
#Gestion de l'humidité de la salle de bain Parentale
binary_sensor:
- platform: generic_hygrostat
  name: Bathroom Hygrostat
  sensor: sensor.station_meteo_module_additionnel_humidity 
  attribute: humidity 
  delta_trigger: 3 
  target_offset: 3 
  min_on_time: 0 
  max_on_time: 7200 
  sample_interval: 300 
  min_humidity: 0 
  unique_id: bathroom_hygrostat 
```

```
- id: 63f7571ed5eb47c18563f4ce9423cf48
  alias: Extraction air SDB ON
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_hygrostat
    to: 'on'
  action:
  - service: switch.turn_on
    entity_id: fan.extracteur_d_air


- id: ced150b901bc452bace306ccd72f0eca
  alias: Extraction air SDB OFF
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_hygrostat
    to: 'off'
  action:
  - service: switch.turn_off
    entity_id: fan.extracteur_d_air

```
