### ISSUE TITLE
Bathroom Hygrostat sensor isn't updating anymore

### ISSUE THREAD

**Issue by rogervdh** [basschipper/homeassistant-generic-hygrostat#55]
Since a few days the Bathroom Hygrostat sensor (binary_sensor.bathroom_hygrostat) isn't updating anymore. The source sensor is still providing data about the humidity and the entity ID of that sensor hasn't changed. Please see the attribute values of the sensor:

![image](https://github.com/user-attachments/assets/acd3fdc6-96fb-4a28-a97a-fec232cef31e)

Sensor providing data:
![image](https://github.com/user-attachments/assets/4443a947-bb74-44ac-9dc8-8cc7eeeb3e0a)

I'm using core 2025.1.2, supervisor 2024.12.3, Operating System 14.1

YAML configuration:
```
# Generic Hygrostat sensor (HACS integration)
binary_sensor:
  - platform: generic_hygrostat
    name: Bathroom Hygrostat
    sensor: sensor.temperatuursensor_badkamer_humidity # Source humidity sensor
    attribute: humidity # Optional use sensor attribute instead of state.
    delta_trigger: 3 # Optional humidity swing to detect. Default = 3
    target_offset: 3 # Optional dehumidification target offset. Default = 3
    min_on_time: 600 # Optional min on time in seconds. Default = 0 seconds
    max_on_time: 2700 # Optional safety max on time in seconds. Default = 7200 seconds
    sample_interval: 300 # Optional time between taking humidity samples in seconds, default 300 seconds
    min_humidity: 0 # Optional minimum humidity to enable dehumidification. Default = 0
    unique_id: bathroom_hygrostat # Optional ID that uniquely identifies this sensor. Set this to a unique value to allow customization through the UI.
```
